### ISSUE TITLE
`Call to undefined method PhpCsFixer\Config::setParallelConfig()`

### ISSUE THREAD

**Issue by Kaishiyoku** [laravel/pint#296]
### Pint Version

1.18.0

### PHP Version

8.2

### Description

I can't run pint on v1.18.0; it worked on v1.17.x.

```
> ./vendor/bin/pint

In ConfigurationFactory.php line 46:

  Call to undefined method PhpCsFixer\Config::setParallelConfig()


Script ./vendor/bin/pint handling the pint event returned with error code 1
```

### Steps To Reproduce

* `composer require laravel/pint --dev`
* run `./vendor/bin/pint`

**Comment by ishan-tripathi-logiclink-labs** [comment]
This is happening in PHP 8.3 too, with V1.18 only.

**Comment by HDVinnie** [comment]
Can confirm getting:

```
In ConfigurationFactory.php line 46:
                                                                   
  Call to undefined method PhpCsFixer\Config::setParallelConfig() 
```

PHP 8.3 and Pint v1.18.0

**Comment by elijahstorm** [comment]
Fixed the issue by locking to:

```
"laravel/pint": "1.17",
```

Would like a fix for this

**Comment by SRWieZ** [comment]
Can confirm too!

**Comment by joetannenbaum** [comment]
This was fixed in v1.18.1!

**Comment by mortenscheel** [comment]
The error may be gone but it still isn't using multiple threads.
